urls.py
import os

from django.conf.urls.defaults import *
from django.conf import settings
from django.views.static import serve

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('thaihealthplm.accounts.urls')),
    (r'^', include('thaihealthplm.administration.urls')),
    (r'^', include('thaihealthplm.domain.urls')),
    (r'^', include('thaihealthplm.homepage.urls')),
    (r'^', include('thaihealthplm.budget.urls')),
    (r'^', include('thaihealthplm.kpi.urls')),
    (r'^', include('thaihealthplm.progress.urls')),
    
    (r'^accounts/', include('registration.backends.default.urls')),
    
    (r'^admin/(.*)', admin.site.root),
    
    
    
    
    (r'^$', 'homepage.views.view_homepage'),
    
)

if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^m/(?P<path>.*)$', serve, {
            'document_root' : os.path.join(os.path.dirname(__file__), "media")
        })
    )

accounts/models.py
from django.contrib.auth.models import User, Group
from django.db import models

class UserAccount(models.Model):
    user = models.ForeignKey(User, unique=True)
    firstname = models.CharField(max_length=300)
    lastname = models.CharField(max_length=300)
    random_password = models.CharField(max_length=30, null=True)

class UserRoleResponsibility(models.Model):
    user = models.ForeignKey('UserAccount')
    role = models.ForeignKey(Group)
    sectors = models.ManyToManyField('domain.Sector', null=True)
    programs = models.ManyToManyField('domain.Program', null=True)

class GroupDetails(models.Model):
    NO_LEVEL = 0
    SECTOR_LEVEL = 1
    PROGRAM_LEVEL = 2
    
    group = models.ForeignKey(Group, unique=True)
    name = models.CharField(max_length=512)
    level = models.IntegerField(default=SECTOR_LEVEL) # Use to determine role responsibility either sectors or programs

class AdminPermission(models.Model):
    permission = models.CharField(max_length=300)

class UserPermission(models.Model):
    role = models.ForeignKey(Group)
    permission = models.CharField(max_length=300)
    only_responsible = models.BooleanField(default=True)

class PermissionName(models.Model):
    permission = models.CharField(max_length=300, unique=True)
    name = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000, default='')

kpi/models.py
from django.db import models

class MasterPlanKPI(models.Model):
    master_plan = models.ForeignKey('domain.MasterPlan')
    ref_no = models.CharField(max_length=100)
    name = models.CharField(max_length=1000)
    abbr_name = models.CharField(max_length=200)
    unit_name = models.CharField(max_length=100)
    enabled = models.BooleanField(default=True)

class MasterPlanKPISchedule(models.Model):
    kpi = models.ForeignKey('MasterPlanKPI')
    program = models.ForeignKey('domain.Program')
    target = models.IntegerField()
    result = models.IntegerField()
    quarter = models.IntegerField() # 1-4
    quarter_year = models.IntegerField() # gregorian calendar year

class MasterPlanKPIScheduleRevision(models.Model):
    schedule = models.ForeignKey('MasterPlanKPISchedule')
    target = models.IntegerField()
    result = models.IntegerField()
    quarter = models.IntegerField() # 1-4
    quarter_year = models.IntegerField() # gregorian calendar year
    revised = models.DateTimeField(auto_now_add=True)
    revised_by = models.ForeignKey('accounts.UserAccount')

class MasterPlanKPIScheduleProjects(models.Model):
    schedule = models.ForeignKey('MasterPlanKPISchedule')
    project = models.ForeignKey('domain.Project')

accounts/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms.util import ErrorList

class ChangeFirstTimePasswordForm(forms.Form):
    password1 = forms.CharField(widget=forms.PasswordInput(), max_length=100, label='รหัสผ่าน')
    password2 = forms.CharField(widget=forms.PasswordInput(), max_length=100, label='ยืนยันรหัสผ่าน')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 != password2:
            self._errors["password2"] = ErrorList(['รหัสผ่านไม่สัมพันธ์กัน'])
            del cleaned_data["password2"]

        return cleaned_data

class ChangeUserProfileForm(forms.Form):
    firstname = forms.CharField(max_length=300, label='ชื่อ')
    lastname = forms.CharField(max_length=300, label='นามสกุล')

class ChangeUserPasswordForm(forms.Form):
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(), label='รหัสผ่าน')
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(), label='ยืนยันรหัสผ่าน')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        
        if password1 != password2:
            self._errors['password2'] = ErrorList(['รหัสผ่านไม่ตรงกัน'])
            del cleaned_data['password1']
            del cleaned_data['password2']
        
        return cleaned_data

templates/page_administration/manage_organization.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
<script type="text/javascript">
$(document).ready(function() {
    $(".delete-sector").click(function(e) {
        if(!window.confirm("ยืนยันการลบสำนัก?")) {
            e.preventDefault();
        }
    });

    $(".delete-master-plan").click(function(e) {
        if(!window.confirm("ยืนยันการลบแผนหลัก?")) {
            e.preventDefault();
        }
    });
});
</script>
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_control_panel">
    <ul>
        <li><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/><a href="{% url view_administration_organization_add_sector %}">เพิ่มสำนัก</a></li>
        {% if sectors %}<li><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/><a href="{% url view_administration_organization_add_masterplan %}">เพิ่มแผนหลัก</a></li>{% endif %}
    </ul>
</div>

<div class="admin_org_page">
    <h2>แผนหลัก</h2>
    {% if master_plans %}
    <table class="ss_table">
        <tr>
            <th></th>
            <th class="ref_no">เลขที่แผน</th>
            <th class="name">ชื่อแผน</th>
            <th class="sector">สำนักที่ดูแล</th>
            <th class="manage"></th>
        </tr>
        {% for master_plan in master_plans %}
        <tr>
            <td class="controls">
                <a href="{% url view_administration_organization_edit_masterplan master_plan.ref_no %}" title="แก้ไขแผนหลัก"><img src="{{MEDIA_URL}}/images/icons/edit.png" class="icon" /></a>
                {% if master_plan.removable %}
                <a href="{% url view_administration_organization_delete_masterplan master_plan.ref_no %}" title="ลบแผนหลัก" class="delete-master-plan"><img src="{{MEDIA_URL}}/images/icons/delete.png" class="icon" /></a>
                {% else %}
				<img src="{{MEDIA_URL}}/images/icons/delete_disabled.png" class="icon" title="ไม่สามารถลบแผนหลักที่มีหน่วยงานภายใต้ได้"/>
                {% endif %}
            </td>
            <td class="ref_no">{{master_plan.ref_no}}</td>
            <td class="name"><a href="{% url view_master_plan_overview master_plan.ref_no %}">{{master_plan.name}}</a></td>
            <td class="sector">{{master_plan.sectors|join:", "}}</td>
            <td class="manage"><img src="{{MEDIA_URL}}/images/icons/manage.png" class="icon"/> <a href="{% url view_master_plan_manage_organization master_plan.id %}">จัดการแผนหลัก</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <div class="ss_no_information">ไม่มีแผนหลัก</div>
    {% endif %}
    
    <h2>สำนัก</h2>
    {% if sectors %}
    <table class="ss_table">
        <tr>
            <th></th>
            <th class="sector_number">เลขสำนัก</th>
            <th class="sector_name">ชื่อสำนัก</th>
        </tr>
        {% for sector in sectors %}
        <tr>
            <td class="controls">
                <a href="{% url view_administration_organization_edit_sector sector.ref_no %}" title="แก้ไขสำนัก"><img src="{{MEDIA_URL}}/images/icons/edit.png" class="icon" /></a>
                {% if sector.removable %}
                <a href="{% url view_administration_organization_delete_sector sector.ref_no %}" title="ลบสำนัก" class="delete-sector"><img src="{{MEDIA_URL}}/images/icons/delete.png" class="icon" /></a>
                {% else %}
				<img src="{{MEDIA_URL}}/images/icons/delete_disabled.png" class="icon" title="ไม่สามารถลบสำนักที่มีแผนหลักได้"/>
                {% endif %}
            </td>
            <td class="sector_number">{{sector.ref_no}}</td>
            <td class="sector_name"><a href="{% url view_sector_overview sector.ref_no %}">{{sector.name}}</a></td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <div class="ss_no_information">ไม่มีสำนัก</div>
    {% endif %}
</div>
{% endblock %}

templates/page_administration/manage_organization_modify_master_plan.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
	<div class="breadcrumbs"><a href="{% url view_administration_organization %}">หน้าโครงสร้างองค์กร</a> &#187;</div>
    <h2>{% if master_plan %}แก้ไขแผนหลัก{% else %}เพิ่มแผนหลัก{% endif %}</h2>
</div>

<form action="." method="post" class="ss_form">
	{% csrf_token %}
	
    {% if has_sectors %}
    <ul>
        <li>
            <label for="id_ref_no" class="caption">{{form.ref_no.label}}{% display_required %}</label>
            <div class="input SHORT">{{form.ref_no}}</div>
            <div class="comment">{{form.ref_no.label}}ต้องประกอบด้วยตัวเลขเท่านั้น</div>
            {{form.ref_no.errors}}
            
        </li>
        <li>
            <label for="id_name" class="caption">{{form.name.label}}{% display_required %}</label>
            <div class="input LONG">{{form.name}}</div>
            {{form.name.errors}}
        </li>
        <li>
            <label for="id_sectors" class="caption">{{form.sectors.label}}{% display_required %}</label>
            <div class="input master_plan_sectors">{{form.sectors}}</div>
            {{form.sectors.errors}}
        </li>
    </ul>
    {{form.master_plan_id}}
    <div class="button_panel"><button>{% if master_plan %}แก้ไขแผนหลัก{% else %}เพิ่มแผนหลัก{% endif %}</button></div>
    {% else %}
    <div class="prerequisute">ยังไม่มีข้อมูลสำนัก กรุณาเพิ่มสำนักก่อนที่หน้า <a href="{% url view_administer_organization_add_sector %}">เพิ่มสำนัก</a></div>
    {% endif %}
</form>
{% endblock %}

templates/page_administration/manage_organization_modify_sector.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_administration_organization %}">หน้าโครงสร้างองค์กร</a> &#187;</div>
    <h2>{% if sector %}แก้ไขสำนัก{% else %}เพิ่มสำนัก{% endif %}</h2>
</div>

<form action="." method="post" class="ss_form">
	{% csrf_token %}
	
    <ul>
        <li>
            <label for="id_ref_no" class="caption">{{form.ref_no.label}}{% display_required %}</label>
            <div class="input SHORT">{{form.ref_no}}</div>
            <div class="comment">{{form.ref_no.label}}ต้องประกอบด้วยตัวเลขเท่านั้น</div>
            {{form.ref_no.errors}}
        </li>
        <li>
            <label for="id_name" class="caption">{{form.name.label}}{% display_required %}</label>
            <div class="input LONG">{{form.name}}</div>
            {{form.name.errors}}
        </li>
    </ul>
    {{form.sector_id}}
    <div class="button_panel"><button>{% if sector %}แก้ไขสำนัก{% else %}เพิ่มสำนัก{% endif %}</button></div>
</form>
{% endblock %}

templates/page_administration/manage_users.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags page_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_control_panel">
    <ul>
        <li><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/><a href="{% url view_administration_users_add %}">สร้างบัญชีผู้ใช้</a></li>
    </ul>
</div>

<div class="admin_users_page">
	{% if user_accounts.object_list %}
	{% display_pagination user_accounts 'view_administration_users' %}
	
	<table class="ss_table">
        <tr>
            <th class="controls"></th>
            <th class="fullname">ชื่อ-นามสกุล</th>
			<th class="username">ชื่อบัญชี</th>
            <th class="status">สถานะบัญชีผู้ใช้</th>
			<th class="role">ตำแหน่ง</th>
        </tr>
		
		{% for user_account in user_accounts.object_list %}
		<tr>
			<td class="controls">
				<a href="{% url view_administration_users_edit user_account.user.id %}" title="แก้ไขข้อมูลผู้ใช้"><img src="{{MEDIA_URL}}/images/icons/edit.png" class="icon" /></a>
				{% if user_account.random_password %}
				<img src="{{MEDIA_URL}}/images/icons/password_disabled.png" class="icon" />
				{% else %}
				<a href="{% url view_administration_users_change_password user_account.user.id %}" title="เปลี่ยนรหัสผ่าน"><img src="{{MEDIA_URL}}/images/icons/password.png" class="icon" /></a>
				{% endif %}
			</td>
			<td class="fullname">{{user_account.firstname}} {{user_account.lastname}}</td>
			<td class="username">{{user_account.user.username}}</td>
			<td class="status">
                {% if user_account.random_password %}
                    ยังไม่เข้าใช้งาน (<a href="{% url view_administration_users_password user_account.user.id %}">ดูรหัสผ่าน</a>)
                {% else %}
                    {% if user_account.user.is_active %}ปกติ{% else %}ระงับการใช้งาน{% endif %}
                {% endif %}
            </td>
			<td class="role">
				<ul>
					{% list_user_roles user_account %}
                </ul>
			</td>
		</tr>
		{% endfor %}
		
	</table>
	
	{% display_pagination user_accounts 'view_administration_users' %}
    {% else %}
    <div class="ss_no_information">ไม่มีผู้ใช้</div>
    {% endif %}
</div>
{% endblock %}

templates/page_administration/manage_users_change_password.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_administration_users %}">รายชื่อผู้ใช้ระบบ</a> &#187;</div>
    <h2>ตั้งรหัสผ่านใหม่</h2>
</div>

<div class="admin_users_page">
	{% if editing_user.get_profile.random_password %}
		<div class="ss_no_information">ผู้ใช้นี้ยังไม่มีการเข้าใช้งาน ให้ใช้รหัสผ่านด้านล่างในการเข้าสู่ระบบ</div>
		<div class="random_password_panel"><span class="label">รหัสผ่าน:</span> {{editing_user.get_profile.random_password}}</div>
		<div><a href="{% url view_administration_users %}">กลับไปหน้ารายชื่อผู้ใช้ &#187;</a></div>
	{% else %}
		<form action='.' method='POST' class="ss_form">
	        <ul>
	            <li>
	                <label for="id_password1" class="caption">{{form.password1.label}}{% display_required %}</label>
	                <div class="input MEDIUM">{{form.password1}}</div>
	                {{form.password1.errors}}
	            </li>
	            <li>
	                <label for="id_password2" class="caption">{{form.password2.label}}{% display_required %}</label>
	                <div class="input MEDIUM">{{form.password2}}</div>
	                {{form.password2.errors}}
	            </li>
	        </ul>
	        <div class="button_panel"><button>ตกลง</button></div>
	    </form>
	{% endif %}
</div>
{% endblock %}

templates/page_administration/manage_users_modify_user.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
<script type="text/javascript">
    $(document).ready(function() {
		$("#id_role").change(function() {
			var role_name = $(this).find("option:selected").val();
			
			$.getJSON('{% url ajax_get_group_level %}', {role_name:role_name}, function(result) {
				if(result == '0') {
					$("li.responsible").hide();
					
				} else if(result == '1') {
					$("li.responsible").show();
					$("li.responsible .sectors").show();
					$("#responsible_sector option:first").attr("selected", "selected");
					$("li.responsible .programs").hide();
					
				} else if(result == '2') {
					$("li.responsible").show();
                    $("li.responsible .sectors").hide();
                    $("li.responsible .programs").show();
					$("#responsible_master_plan option:first").attr("selected", "selected");
					
					$("#responsible_selected_programs").html("");
					$("#responsible_programs").hide();
				}
			});
		});
		
		$("#responsible_master_plan").change(function() {
			var master_plan_id = $(this).find("option:selected").val();
			
			if(master_plan_id) {
				$.getJSON("{% url ajax_get_master_plan_programs %}", {master_plan_id:master_plan_id}, function(data) {
	                var options = "";
					
					if(data.length == 0) {
						$("#responsible_programs").html("<option>ไม่มีแผนงาน</option>");
						$("#responsible_programs").attr("disabled", "disabled");
					} else {
						for(var i=0; i<data.length; i++) {
	                        options = options + '<option value="' + data[i].id + '">' + data[i].ref_no + ' ' + data[i].name + '</option>';
	                    }
	                    
	                    $("#responsible_programs").html("<option></option>" + options);
						$("#responsible_programs").attr("disabled", "");
					}
	                
	                $("#responsible_programs").show();
	            });
			}
		});
		
		$("#responsible_programs").change(function() {
			var program_id = $(this).find("option:selected").val();
			
			if (program_id) {
				// Check Duplicated
				var duplicated = false;
				
				$("#responsible_selected_programs li").each(function() {
					var split = $(this).attr("class").split("-");
					if(split[1] == program_id) duplicated = true;
				});
				
				if(!duplicated) {
					// Add to list
	                var program_name = $(this).find("option:selected").text();
	                
	                var new_program = $('<li class="program-' + program_id + '"><a href="#" class="remove-program"><img src="{{MEDIA_URL}}/images/icons/delete_row.png" class="icon"/></a>แผนงาน ' + program_name + '</li>');
	                new_program.find(".remove-program").click(function(e) {
	                    e.preventDefault();
	                    $(this).closest("li").remove();
	                });
	                
	                new_program.appendTo("#responsible_selected_programs");
				}
				
				// Clear Input
				$("#responsible_master_plan option:first").attr("selected", "selected");
				$("#responsible_programs").html("");
				$("#responsible_programs").hide();
			}
		});
		
		$("#responsible_selected_programs .remove-program").click(function(e) {
			e.preventDefault();
            $(this).closest("li").remove();
		});
		
		$(".button_panel button").click(function() {
            if($("li.responsible .sectors").is(":visible")) {
				var sector_id = $("#responsible_sector option:selected").val();
				$("#responsible_input").html('<input type="hidden" name="responsible_sector" value="' + sector_id + '" />');
			}
			
			if($("li.responsible .programs").is(":visible")) {
                var input_html = "";
				$("#responsible_selected_programs li").each(function() {
					var split = $(this).attr("class").split("-");
					var program_id = split[1];
					input_html = input_html + '<input type="hidden" name="responsible_program" value="' + program_id + '" />';
				});
				$("#responsible_input").html(input_html);
            }
			
			return true;
        });
	});
</script>


{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_administration_users %}">รายชื่อผู้ใช้ระบบ</a> &#187;</div>
    <h2>{% if not editing_user %}เพิ่มผู้ใช้{% else %}แก้ไขผู้ใช้{% endif %}</h2>
</div>

<div class="admin_users_page">
<form action='.' method='POST' class="ss_form">
	{% csrf_token %}
	
    <ul>
        <li>
            <label for="id_username" class="caption">{{form.username.label}}{% display_required %}</label>
            <div class="input MEDIUM">{{form.username}}</div>
            <div class="comment">ชื่อที่ใช้ในการเข้าสู่ระบบ</div>
            {{form.username.errors}}
        </li>
        <li>
            <label for="id_email" class="caption">{{form.email.label}}{% display_required %}</label>
            <div class="input MEDIUM">{{form.email}}</div>
            {{form.email.errors}}
        </li>
        <li>
            <label for="id_firstname" class="caption">{{form.firstname.label}}{% display_required %}</label>
            <div class="input MEDIUM">{{form.firstname}}</div>
            {{form.firstname.errors}}
        </li>
        <li>
            <label for="id_lastname" class="caption">{{form.lastname.label}}{% display_required %}</label>
            <div class="input MEDIUM">{{form.lastname}}</div>
            {{form.lastname.errors}}
        </li>
        <li>
            <label for="id_role" class="caption">{{form.role.label}}{% display_required %}</label>
            <div class="input">{{form.role}}</div>
            {{form.role.errors}}
        </li>
		<li class="responsible" {% if not responsible_sector and not responsible_programs %}style="display:none"{% endif %}>
			<label for="id_responsible" class="caption">หน่วยงานที่รับผิดชอบ:</label>
			<div class="input">
				<div class="sectors" {% if not responsible_sector %}style="display:none"{% endif %}>
					<div class="list"><select id="responsible_sector">{% for sector in sectors %}<option value="{{sector.id}}" {% ifequal sector.id responsible_sector.id %}selected="selected"{% endifequal %}>สำนัก {{sector.ref_no}} - {{sector.name}}</option>{% endfor %}</select></div>
				</div>
				<div class="programs" {% if not responsible_programs %}style="display:none"{% endif %}>
					<div><ul id="responsible_selected_programs">{% for responsible_program in responsible_programs %}<li class="program-{{responsible_program.id}}"><a href="#" class="remove-program"><img src="{{MEDIA_URL}}/images/icons/delete_row.png" class="icon"/></a>แผนงาน {{responsible_program.ref_no}} - {{responsible_program.name}}</li>{% endfor %}</ul></div>
					<div class="list"><select id="responsible_master_plan"><option></option>{% for master_plan in master_plans %}<option value="{{master_plan.id}}">แผน {{master_plan.ref_no}}</option>{% endfor %}</select> <span class="list_comment">* เลือกแผนหลัก จากนั้นเลือกแผนงาน</span></div>
					<div class="list"><select id="responsible_programs" style="display:none"></select></div>
				</div>
				
				<div id="responsible_input"></div>
			</div>
		</li>
    </ul>
    
    <div class="button_panel"><button>ตกลง</button></div>
</form>
</div>

{% endblock %}

templates/page_administration/manage_users_password.html
{% extends 'page_base.html' %}
{% load helper_tags tab_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}<h1>การจัดการระบบ</h1>{% endblock %}

{% block body_tabs %}{% tabs_for_administration page %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_administration_users %}">รายชื่อผู้ใช้ระบบ</a> &#187;</div>
    <h2>รหัสผ่านผู้ใช้</h2>
</div>

<div class="admin_users_page">
	<div class="user_password">
    {% if new_user_account.random_password %}
        <div class="name">{{new_user_account.first_name}} {{new_user_account.last_name}}</div>
        <div class="name">ชื่อผู้ใช้: {{new_user_account.user.username}}</div>
        <div class="password">รหัสผ่าน: {{new_user_account.random_password}}</div>
        <div class="note">* รหัสผ่านนี้ใช้สำหรับการเข้าสู่ระบบครั้งแรกเท่านั้น</div>
    {% else %}
        <div class="warning">ผู้ใช้นี้เปลี่ยนรหัสผ่านเป็นของตัวเองแล้ว คุณไม่สามารถดูรหัสผ่านได้</div>
    {% endif %}
	<a href="{% url view_administration_users %}">กลับไปหน้ารายชื่อผู้ใช้ &#187;</a>
	</div>
</div>
{% endblock %}