urls.py
import os

from django.conf.urls.defaults import *
from django.conf import settings
from django.views.static import serve

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('thaihealthplm.accounts.urls')),
    (r'^', include('thaihealthplm.administration.urls')),
    (r'^', include('thaihealthplm.domain.urls')),
    (r'^', include('thaihealthplm.homepage.urls')),
    (r'^', include('thaihealthplm.budget.urls')),
    (r'^', include('thaihealthplm.kpi.urls')),
    (r'^', include('thaihealthplm.progress.urls')),
    
    (r'^accounts/', include('registration.backends.default.urls')),
    
    (r'^admin/(.*)', admin.site.root),
    
    
    
    
    (r'^$', 'homepage.views.view_homepage'),
    
)

if settings.DEBUG:
    urlpatterns += patterns('', 
        (r'^m/(?P<path>.*)$', serve, {
            'document_root' : os.path.join(os.path.dirname(__file__), "media")
        })
    )

budget/models.py
from django.db import models

class MasterPlanBudget(models.Model):
    master_plan = models.ForeignKey('domain.MasterPlan')
    budget = models.IntegerField(default=0) # budget amount from board
    year = models.IntegerField() # gregorian calendar year

class MasterPlanBudgetRevision(models.Model):
    budget = models.ForeignKey('MasterPlanBudget')
    budget = models.IntegerField()
    year = models.IntegerField()
    revised = models.DateTimeField(auto_now_add=True)
    revised_by = models.ForeignKey('accounts.UserAccount')

class PlanBudget(models.Model):
    plan = models.ForeignKey('domain.Plan')
    budget = models.IntegerField(default=0) # budget amount that sector planned
    year = models.IntegerField() # gregorian calendar year

class PlanBudgetRevision(models.Model):
    budget = models.ForeignKey('PlanBudget')
    budget = models.IntegerField()
    year = models.IntegerField()
    revised = models.DateTimeField(auto_now_add=True)
    revised_by = models.ForeignKey('accounts.UserAccount')

class ProgramBudgetSchedule(models.Model):
    program = models.ForeignKey('domain.Program')
    grant_budget = models.IntegerField(default=0)
    claim_budget = models.IntegerField(default=0)
    schedule_on = models.DateField()

class ProgramBudgetScheduleRevision(models.Model):
    schedule = models.ForeignKey('ProgramBudgetSchedule')
    grant_budget = models.IntegerField()
    claim_budget = models.IntegerField()
    schedule_on = models.DateField()
    revised = models.DateTimeField(auto_now_add=True)
    revised_by = models.ForeignKey('accounts.UserAccount')

class ClaimReport(models.Model):
    schedule = models.ForeignKey('ProgramBudgetSchedule')
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey('accounts.UserAccount')

class ClaimReportAttachment(models.Model):
    report = models.ForeignKey('ClaimReport')
    filename = models.CharField(max_length=500)

class ClaimReportProjects(models.Model):
    report = models.ForeignKey('ClaimReport')
    project = models.ForeignKey('domain.Project')

kpi/models.py
from django.db import models

class MasterPlanKPI(models.Model):
    master_plan = models.ForeignKey('domain.MasterPlan')
    ref_no = models.CharField(max_length=100)
    name = models.CharField(max_length=1000)
    abbr_name = models.CharField(max_length=200)
    unit_name = models.CharField(max_length=100)
    enabled = models.BooleanField(default=True)

class MasterPlanKPISchedule(models.Model):
    kpi = models.ForeignKey('MasterPlanKPI')
    program = models.ForeignKey('domain.Program')
    target = models.IntegerField()
    result = models.IntegerField()
    quarter = models.IntegerField() # 1-4
    quarter_year = models.IntegerField() # gregorian calendar year

class MasterPlanKPIScheduleRevision(models.Model):
    schedule = models.ForeignKey('MasterPlanKPISchedule')
    target = models.IntegerField()
    result = models.IntegerField()
    quarter = models.IntegerField() # 1-4
    quarter_year = models.IntegerField() # gregorian calendar year
    revised = models.DateTimeField(auto_now_add=True)
    revised_by = models.ForeignKey('accounts.UserAccount')

class MasterPlanKPIScheduleProjects(models.Model):
    schedule = models.ForeignKey('MasterPlanKPISchedule')
    project = models.ForeignKey('domain.Project')

domain/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms.util import ErrorList

from domain.models import *

from widgets import YUICalendar

# FIELD CLASSES

class SectorChoiceField(forms.ModelChoiceField):
	def __init__(self, *args, **kwargs):
		kwargs['empty_label'] = None
		kwargs['queryset'] = Sector.objects.all().order_by('ref_no')
		forms.ModelChoiceField.__init__(self, *args, **kwargs)
	
	def label_from_instance(self, obj):
		return '%d %s' % (obj.ref_no, obj.name)

class SectorCheckboxChoiceField(forms.ModelMultipleChoiceField):
	widget = forms.CheckboxSelectMultiple
	
	def __init__(self, *args, **kwargs):
		kwargs['empty_label'] = None
		kwargs['queryset'] = Sector.objects.all().order_by('ref_no')
		forms.ModelChoiceField.__init__(self, *args, **kwargs)
	
	def label_from_instance(self, obj):
		return '%d %s' % (obj.ref_no, obj.name)

class MasterPlanChoiceField(forms.ModelChoiceField):
	def __init__(self, *args, **kwargs):
		kwargs['empty_label'] = None
		kwargs['queryset'] = MasterPlan.objects.all().order_by('ref_no')
		forms.ModelChoiceField.__init__(self, *args, **kwargs)
	
	def label_from_instance(self, obj):
		return '%d %s' % (obj.ref_no, obj.name)

class PlanChoiceField(forms.ModelChoiceField):
	def __init__(self, *args, **kwargs):
		kwargs['empty_label'] = None
		kwargs['queryset'] = Plan.objects.all().order_by('master_plan__ref_no', 'ref_no')
		forms.ModelChoiceField.__init__(self, *args, **kwargs)
	
	def label_from_instance(self, obj):
		return unicode('%s %s', 'utf-8') % (obj.ref_no, obj.name)

# FORM CLASSES

class ModifyPlanForm(forms.Form):
	def __init__(self, *args, **kwargs):
		self.master_plan = kwargs.pop('master_plan', None)
		forms.Form.__init__(self, *args, **kwargs)
	
	plan_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
	ref_no = forms.CharField(max_length=512, label='รหัส')
	name = forms.CharField(max_length=512, label='ชื่อกลุ่มแผนงาน')
	
	def clean(self):
		cleaned_data = self.cleaned_data
		plan_id = cleaned_data.get('plan_id')
		ref_no = cleaned_data.get('ref_no')
		
		if plan_id: existing = Plan.objects.filter(ref_no=ref_no, master_plan=self.master_plan).exclude(id=plan_id).count()
		else: existing = Plan.objects.filter(ref_no=ref_no, master_plan=self.master_plan).count()
		
		if existing:
			self._errors['ref_no'] = ErrorList(['เลขที่กลุ่มแผนงานนี้ซ้ำกับกลุ่มแผนงานอื่นในแผนหลักเดียวกัน'])
			del cleaned_data['ref_no']
		
		return cleaned_data

class MasterPlanProgramForm(forms.Form):
	def __init__(self, *args, **kwargs):
		master_plan = kwargs.pop('master_plan', None)
		forms.Form.__init__(self, *args, **kwargs)
		
		if master_plan:
			self.fields["plan"].queryset = Plan.objects.filter(master_plan=master_plan).order_by('master_plan__ref_no', 'ref_no')
			self.master_plan = master_plan
	
	program_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
	plan = PlanChoiceField(label="กลุ่มแผนงาน")
	ref_no = forms.CharField(max_length=64, label='เลขที่แผนงาน')
	name = forms.CharField(max_length=1024, label='ชื่อแผนงาน')
	abbr_name = forms.CharField(max_length=200, label='ชื่อย่อแผนงาน')
	manager_name = forms.CharField(max_length=300, label='ผู้ดูแลแผนงาน')
	start_date = forms.DateField(widget=YUICalendar(attrs={'id':'id_start_date'}), label='ระยะเวลา', required=False)
	end_date = forms.DateField(widget=YUICalendar(attrs={'id':'id_end_date'}), label='ถึง', required=False)
	
	def clean(self):
		cleaned_data = self.cleaned_data
		start_date = cleaned_data.get('start_date')
		end_date = cleaned_data.get('end_date')
		
		if start_date > end_date:
			self._errors['start_date'] = ErrorList(['วันที่เริ่มต้นเกิดขึ้นหลังจากวันที่สิ้นสุด'])
			del cleaned_data['start_date']
		
		ref_no = cleaned_data.get('ref_no')
		program_id = cleaned_data.get('program_id')
		
		if program_id: existing = Program.objects.filter(ref_no=ref_no, plan__master_plan=self.master_plan).exclude(id=program_id).count()
		else: existing = Program.objects.filter(ref_no=ref_no, plan__master_plan=self.master_plan).count()
		
		if existing:
			self._errors['ref_no'] = ErrorList(['เลขที่แผนงานนี้ซ้ำกับแผนงานอื่นในแผนหลัก'])
			del cleaned_data['ref_no']
		
		return cleaned_data

class ModifyProjectForm(forms.Form):
	parent_project_id = forms.IntegerField(widget=forms.HiddenInput())
	project_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
	ref_no = forms.CharField(required=False, max_length=64, label='เลขที่โครงการ')
	contract_no = forms.CharField(max_length=200, label='เลขที่สัญญา', required=False)
	name = forms.CharField(max_length=512, label='ชื่อโครงการ')
	start_date = forms.DateField(required=False, widget=YUICalendar(attrs={'id':'id_start_date'}), label='ระยะเวลาโครงการ')
	end_date = forms.DateField(required=False, widget=YUICalendar(attrs={'id':'id_end_date'}), label='ถึง')
	
	def clean(self):
		cleaned_data = self.cleaned_data
		start_date = cleaned_data.get('start_date')
		end_date = cleaned_data.get('end_date')
		
		if start_date > end_date:
			self._errors['start_date'] = ErrorList(['วันที่เริ่มต้นเกิดขึ้นหลังจากวันที่สิ้นสุด'])
			del cleaned_data['start_date']
		
		parent_project_id = cleaned_data.get('parent_project_id')
		project_id = cleaned_data.get('project_id')
		ref_no = cleaned_data.get('ref_no')
		
		if ref_no:
			parent_project = Project.objects.get(pk=parent_project_id)
			
			if project_id: existing = Project.objects.filter(ref_no=ref_no, parent_project=parent_project).exclude(parent_project=None).exclude(id=project_id).count()
			else: existing = Project.objects.filter(ref_no=ref_no, parent_project=parent_project).exclude(parent_project=None).count()
			
			if existing:
				self._errors['ref_no'] = ErrorList(['เลขที่โครงการนี้ซ้ำกับโครงการอื่นในแผนงาน'])
				del cleaned_data['ref_no']
			
		return cleaned_data

class ActivityForm(forms.Form):
	name 			= forms.CharField(max_length=1024, label='ชื่อกิจกรรม')
	start_date      = forms.DateField(widget=YUICalendar(attrs={'id':'id_start_date'}), label='เริ่มตั้งแต่วันที่', required=False)
	end_date        = forms.DateField(widget=YUICalendar(attrs={'id':'id_end_date'}), label='ถึง', required=False)
	description 	= forms.CharField(max_length=2000, required=False, widget=forms.Textarea(), label='รายละเอียด')
	location 		= forms.CharField(max_length=2000, required=False, label='สถานที่')
	result_goal 	= forms.CharField(max_length=2000, required=False, widget=forms.Textarea(), label='ผลลัพธ์ที่ต้องการ')
	result_real 	= forms.CharField(max_length=2000, required=False, widget=forms.Textarea(), label='ผลลัพธ์ที่เกิดขึ้น')
	
	def clean(self):
		cleaned_data = self.cleaned_data
		start_date = cleaned_data.get('start_date')
		end_date = cleaned_data.get('end_date')
		
		if start_date > end_date:
			self._errors['start_date'] = ErrorList(['วันที่เริ่มต้นเกิดขึ้นหลังจากวันที่สิ้นสุด'])
			del cleaned_data['start_date']
		
		return cleaned_data

templates/page_sector/manage_master_plan/manage_modify_plan.html
{% extends 'page_base.html' %}
{% load helper_tags page_tags tab_tags %}

{% block html_head %}
{% endblock %}

{% block body_title %}{% display_master_plan_management_header user master_plan %}{% endblock %}
{% block body_tabs %}{% tabs_for_manage_master_plan page master_plan %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_master_plan_manage_organization master_plan.ref_no %}">หน้าแผนงาน/โครงการ</a> &#187;</div>
    <h2>{% if master_plan %}แก้ไขกลุ่มแผนงาน{% else %}เพิ่มกลุ่มแผนงาน{% endif %}</h2>
</div>

<form action="." method="post" class="ss_form">
    {% csrf_token %}
	<ul>
        <li>
            <label for="id_ref_no" class="caption">{{form.ref_no.label}}{% display_required %}</label>
            <div class="input SHORT">{{form.ref_no}}</div>
            <div class="comment">ประกอบด้วยตัวเลขหรือตัวหนังสือ ความยาวไม่เกิน 64 ตัวอักษร</div>
            {{form.ref_no.errors}}
        </li>
        <li>
            <label for="id_name" class="caption">{{form.name.label}}{% display_required %}</label>
            <div class="input LONG">{{form.name}}</div>
            {{form.name.errors}}
        </li>
    </ul>
    {{form.plan_id}}
    <div class="button_panel"><button type="submit">ตกลง</button></div>
</form>

{% endblock %}

templates/page_sector/manage_master_plan/manage_modify_program.html
{% extends 'page_base.html' %}
{% load helper_tags page_tags tab_tags %}

{% block html_head %}
{{form.media}}
{% endblock %}

{% block body_title %}{% display_master_plan_management_header user master_plan %}{% endblock %}
{% block body_tabs %}{% tabs_for_manage_master_plan page master_plan %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_master_plan_manage_organization master_plan.ref_no %}">หน้าแผนงาน/โครงการ</a> &#187;</div>
    {% if program %}<div class="supertitle">({{program.ref_no}}) {{program.name}}</div>{% endif %}
	<h2>{% if not program %}เพิ่มแผนงาน/โครงการ{% else %}แก้ไขแผนงาน/โครงการ{% endif %}</h2>
</div>

<form action="" method="POST" class="ss_form">
	{% csrf_token %}
	
    <ul>
        <li>
            <label for="id_plan" class="caption">{{form.plan.label}}{% display_required %}</label>
            <div class="input">{{form.plan}}</div>
            {{form.plan.errors}}
        </li>
        <li>
            <label for="id_ref_no" class="caption">{{form.ref_no.label}}{% display_required %}</label>
            <div class="input SHORT">{{form.ref_no}}</div>
            <div class="comment">ประกอบด้วยตัวเลขหรือตัวหนังสือ ความยาวไม่เกิน 64 ตัวอักษร</div>
            {{form.ref_no.errors}}
        </li>
        <li>
            <label for="id_name" class="caption">{{form.name.label}}{% display_required %}</label>
            <div class="input LONG">{{form.name}}</div>
            {{form.name.errors}}
        </li>
		<li>
            <label for="id_abbr_name" class="caption">{{form.abbr_name.label}}</label>
            <div class="input MEDIUM">{{form.abbr_name}}</div>
            {{form.abbr_name.errors}}
        </li>
        <li class="date_period">
            <label class="caption">{{form.start_date.label}}</label>
            <div class="input">{{form.start_date}} <span class="to">{{form.end_date.label}}</span> {{form.end_date}}</div>
            {{form.start_date.errors}}
            {{form.end_date.errors}}
        </li>
		<li>
            <label for="id_manager_name" class="caption">{{form.manager_name.label}}</label>
            <div class="input MEDIUM">{{form.manager_name}}</div>
            {{form.manager_name.errors}}
        </li>
    </ul>
    {{form.program_id}}
    <div class="button_panel">
    	<button type="submit">{% if not program %}เพิ่มแผนงาน/โครงการ{% else %}แก้ไขแผนงาน/โครงการ{% endif %}</button>
	</div>
</form>
{% endblock %}

templates/page_sector/manage_master_plan/manage_organization.html
{% extends 'page_base.html' %}
{% load helper_tags page_tags tab_tags %}

{% block html_head %}
<script type="text/javascript">
$(document).ready(function() {
    $(".delete-plan").click(function(e) {
        if(!window.confirm("ยืนยันการลบกลุ่มแผนงาน?")) {
            e.preventDefault();
        }
    });
    
    $(".delete-program").click(function(e) {
        if(!window.confirm("ยืนยันการลบแผนงาน?")) {
            e.preventDefault();
        }
    });
});
</script>
{% endblock %}

{% block body_title %}{% display_master_plan_management_header user master_plan %}{% endblock %}
{% block body_tabs %}{% tabs_for_manage_master_plan page master_plan %}{% endblock %}

{% block body_content %}
<div class="ss_control_panel">
    <ul>
        <li><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/><a href="{% url view_master_plan_add_plan master_plan.ref_no %}">เพิ่มกลุ่มแผนงาน</a></li>
        {% if plans %}<li><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/><a href="{% url view_master_plan_add_program master_plan.ref_no %}">เพิ่มแผนงาน/โครงการ</a></li>{% endif %}
    </ul>
</div>

<div class="master_plan_manage">
    {% if plans %}
    <table class="ss_table">
        <tr>
        	<th></th>
			<th class="name">แผนงาน/โครงการ</th>
			<th class="date_span">ระยะเวลา</th>
        </tr>
        {% for plan in plans %}
            <tr class="plan">
            	
                <td class="controls">
                    <a href="{% url view_master_plan_edit_plan plan.id %}" title="แก้ไขกลุ่มแผนงาน"><img src="{{MEDIA_URL}}/images/icons/edit.png" class="icon" /></a>
                    {% if plan.programs %}
                    <img src="{{MEDIA_URL}}/images/icons/delete_disabled.png" class="icon" title="ไม่สามารถลบกลุ่มแผนงานที่มีแผนงานได้"/>
                    {% else %}
                    <a href="{% url view_master_plan_delete_plan plan.id %}" title="ลบกลุ่มแผนงาน" class="delete-plan"><img src="{{MEDIA_URL}}/images/icons/delete.png" class="icon" /></a>
                    {% endif %}
                </td>
				<td colspan="2">กลุ่มแผนงาน: ({{plan.ref_no}}) {{plan.name}}</td>
            </tr>
            {% if plan.programs %}
            {% for program in plan.programs %}
                <tr>
                	<td></td>
                    <td class="name">
                    	<div class="title">รหัสแผนงาน/โครงการ: {{program.ref_no}}</div>
                    	<a href="{% url view_program_overview program.id %}">{{program.name}}</a>
						<div class="subcontrols">
							<img src="{{MEDIA_URL}}/images/icons/row_edit.png" class="icon" /> <a href="{% url view_master_plan_edit_program program.id %}">แก้ไข</a>
							<span>|</span>
							<a href="{% url view_master_plan_program_kpi program.id %}">จัดการแผนผลลัพธ์</a>
							<span>|</span>
							<a href="{% url view_master_plan_program_budget program.id %}">จัดการแผนการเงิน</a>
							{% if program.removable %}
							<span>|</span>
							<a href="{% url view_master_plan_delete_program program.id %}" class="delete-program">ลบแผนงาน</a>
							{% endif %}
						</div>
					</td>
					<td class="date_span">
						{% if program.start_date and program.end_date %}
							<div>{{program.start_date|full_date}}</div>
							<div class="to">ถึง</div>
							<div>{{program.end_date|full_date}}</div>
						{% else %}ยังไม่กำหนด{% endif %}
					</td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
            	<td></td>
                <td colspan="2" class="table_no_information">ไม่มีแผนงานภายใต้กลุ่มแผนงานนี้</td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>
    {% else %}
    <div class="ss_no_information">ไม่มีข้อมูลกลุ่มแผนงาน</div>
    {% endif %}
</div>
{% endblock %}

templates/page_sector/manage_master_plan/manage_program_budget.html
{% extends 'page_base.html' %}
{% load helper_tags page_tags tab_tags humanize %}

{% block html_head %}
<link href="{{MEDIA_URL}}/yui/build/container/assets/skins/sam/container.css" type="text/css" media="all" rel="stylesheet" />
<link href="{{MEDIA_URL}}/yui/build/calendar/assets/skins/sam/calendar.css" type="text/css" media="all" rel="stylesheet" />

<link href="{{MEDIA_URL}}/css/yui.calendar.widget.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="{{MEDIA_URL}}/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}/yui/build/element/element-min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}/yui/build/container/container-min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}/yui/build/calendar/calendar-min.js"></script>
<script type="text/javascript" src="{{MEDIA_URL}}/scripts/yui.calendar.widget.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    $(".new-schedule").click(function(e) {
        e.preventDefault();
        var uid = new Date().getTime();
        var new_row = $('<tr class="schedule"><td class="actions"><a href="#" class="remove-schedule">ลบ</a></td><td class="grant_column"><input type="text" /> บาท</td><td class="schedule_on_column"><span class="yui_date_picker_panel"><input type="hidden" name="schedule_on" value="" id="id_schedule_on_' + uid + '_value"/><input type="text" value="" id="id_schedule_on_' + uid + '_display" readonly="readonly" class="yui_date_picker_textbox"/> <img src="/m/images/icons/date_picker.png" id="id_schedule_on_' + uid + '" class="yui_date_picker"/></span></td><td></td></tr>');
        initializeRowEvents(new_row);
        new_row.insertBefore($(this).closest('tr'));
    });
    
    $("table tr.schedule").each(function(e) {
        initializeRowEvents($(this));
    });
    
    $("form button[type='submit']").click(function() {
        var is_valid = true;
        $(".error_message.invalid_input").hide();
        
        $("table tr.schedule").each(function() {
            // Schedule ID
            var schedule_id = $(this).attr("id");
            if(schedule_id) {
                schedule_id = schedule_id.split("-")[1];
            } else {
                schedule_id = 'none';
            }
            
            // Grant
            var target = $(this).find(".grant_column input").val();
            if(target == "") {
                is_valid = false;
                $(this).find(".grant_column input").addClass("invalid");
                $(".error_message.invalid_input").show();
            } else {
                target = to_number(target);
                if(target == null) {
                    is_valid = false;
                    $(this).find(".grant_column input").addClass("invalid");
                    $(".error_message.invalid_input").show();
                } else {
                    $(this).find(".grant_column input").removeClass("invalid");
                }
            }
            
            // Schedule On
            var schedule_on = $(this).find("input[name='schedule_on']").val();
            if(schedule_on == "") {
                is_valid = false;
                $(this).find("input[name='schedule_on']").addClass("invalid");
            } else {
                $(this).find("input[name='schedule_on']").removeClass("invalid");
            }
            
            if(is_valid) {
                var schedule_text = schedule_id + "," + target + "," + schedule_on;
                $("form").append('<input type="hidden" name="schedule" value="' + schedule_text + '" />');
            }
        });
        
        return is_valid;
    });
});

function initializeRowEvents(row_obj) {
    row_obj.find(".grant_column input").digits()
    
    row_obj.find(".remove-schedule").click(function(e) {
        e.preventDefault();
        if(window.confirm("ยืนยันการลบ?")) {
            $(this).closest("tr").remove();
        }
    });
    
    row_obj.find(".yui_date_picker").click(function(e) {
        activeCalendarInputID = e.target.id;
        triggerYUICalendar();
    });
        
    // Open Date Picker calendar when click at textbox
    row_obj.find(".yui_date_picker_textbox").click(function(e) {
        activeCalendarInputID = $(this).parent().find(".yui_date_picker").attr('id');
        triggerYUICalendar();
    });
}
</script>
{% endblock %}

{% block body_title %}{% display_master_plan_management_header user master_plan %}{% endblock %}
{% block body_tabs %}{% tabs_for_manage_master_plan page master_plan %}{% endblock %}

{% block body_content %}
<div class="ss_breadcrumbs">
    <div class="breadcrumbs"><a href="{% url view_master_plan_manage_organization master_plan.ref_no %}">หน้าแผนงาน/โครงการ</a> &#187;</div>
    <div class="supertitle">({{program.ref_no}}) {{program.name}}</div>
	<h2>จัดการแผนการเงิน</h2>
</div>

<div class="master_plan_manage">
    <div class="error_message invalid_input" style="display:none;">ข้อมูลไม่ครบถ้วนหรือไม่อยู่ในรูปแบบที่ถูกต้อง</div>
    
    <div class="manage_program_budget">
        <table class="ss_table">
            <tr>
                <th class="controls"></th>
                <th class="grant_column">ตัวเลขคาดการณ์</th>
                <th class="schedule_on_column">วันที่เบิกจ่าย</th>
                <th></th>
            </tr>
            {% if schedules %}
                {% for schedule in schedules %}
                <tr class="schedule" id="schedule-{{schedule.id}}">
                    <td class="controls"><a href="#" class="remove-schedule">ลบ</a></td>
                    <td class="grant_column"><input type="text" value="{{schedule.grant_budget|intcomma}}"/> บาท</td>
                    <td class="schedule_on_column">
                        <span class="yui_date_picker_panel">
                            <input type="hidden" name="schedule_on" value="{{schedule.schedule_on|date:"Y-n-j"}}" id="id_schedule_on_{{schedule.id}}_value"/>
                            <input type="text" value="{{schedule.schedule_on|date:"j F"}} {{schedule.schedule_on.year|add:543}}" id="id_schedule_on_{{schedule.id}}_display" readonly="readonly" class="yui_date_picker_textbox"/>
                            <img src="/m/images/icons/date_picker.png" id="id_schedule_on_{{schedule.id}}" class="yui_date_picker"/>
                        </span>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                {% endfor %}
            {% else %}
            <tr class="schedule">
                <td class="actions"><a href="#" class="remove-schedule">ลบ</a></td>
                <td class="grant_column"><input type="text" /> บาท</td>
                <td class="schedule_on_column">
                    <span class="yui_date_picker_panel">
                        <input type="hidden" name="schedule_on" value="" id="id_schedule_on_starter_value"/>
                        <input type="text" value="" id="id_schedule_on_starter_display" readonly="readonly" class="yui_date_picker_textbox"/>
                        <img src="/m/images/icons/date_picker.png" id="id_schedule_on_starter" class="yui_date_picker"/>
                    </span>
                </td>
                <td>&nbsp;</td>
            </tr>
            {% endif %}
            <tr>
                <td></td>
                <td colspan="3"><img src="{{MEDIA_URL}}/images/icons/create.png" class="icon"/> <a href="#" class="new-schedule">เพิ่มรายการ</a></td>
            </tr>
        </table>
        
        <form action="." method="POST" class="ss_form">
        	{% csrf_token %}
			{% back_form request %}
            <div class="button_panel"><button type="submit">บันทึกการแก้ไข</button></div>
        </form>
    </div>
</div>
{% endblock %}